Add missing UnixDomainSocketConnection._buffer_cutoff
Without this using `unix_socket_path` will fail:

    AttributeError: 'UnixDomainSocketConnection' object has no attribute '_buffer_cutoff'

Fixes #1067