pubsub: improve error reporting if caller forgets to subscribe
This is an easy mistake to make -- at least, I keep making it. It
formerly resulted in a confusing crash, "AttributeError: 'NoneType'
object has no attribute 'can_read'", from parse_response(). I have had
to dig into the redis-py source code more than once to figure out what
went wrong.

With this patch, it still crashes, but with a clearer error that
clarifies what the calling code forgot to do.

Fixes issue #716.